### ISSUE TITLE
ASpli work for low read depth

### ISSUE THREAD

**Issue by OnkarMulay** [estepi/ASpli#19]
Hi,

I have fastq files for a few samples with very low read depth. I wanted to know if ASpli works well on them to give good events?
Certainly, other tools don't perform well for samples with lower read depth.

PLease let me know about your suggestions

**Comment by estepi** [comment]
Hi Onkar,

In ASpli you have no restrictions in term of coverage for your analysis but the package uses coverage to filter genes and events for minimun quality. At the end of the day, if you have a low low coverage sequencing, you will get information only on those highly expressed genes. You can try and tell us how many genes do you well map using ASpli.

Sorry for the delay, happy to help you

**Comment by UnnikrishnanLab** [comment]
Ok, that's great I can post it in the same issue. And will then close it.

**Comment by OnkarMulay** [comment]
Ok, that's great, I can work it out and post it here and then close the issue.

**Comment by estepi** [comment]
It is better you close this one and paste answer in our formal repo:
https://github.com/chernolab/ASpli

thanks!
