### ISSUE TITLE
All NAs using ASpli for all splicing events

### ISSUE THREAD

**Issue by OnkarMulay** [estepi/ASpli#20]
I had run ASpli for 24 samples 12 and 22 in  each group.  I got reports for : 
asd <- jCounts(counts=gbcounts, features=features, minReadLength=200)  --> all NAs 

Code:

library("ASpli")
library("GenomicFeatures")
library("statmod")

# GTF Preprocessing -----
gtfFileName <- "/scratch/zq45/om4416/HomoSapiens/Homo_sapiens.GRCh38.100.chr.gtf"
genomeTxDb  <- makeTxDbFromGFF(gtfFileName)

# Feature Extraction ----
features    <- binGenome( genomeTxDb )

# Bam and Traget ------
BAMFiles <- c("bam1_1/Aligned.sortedByCoord.out.bam","bam1_2/Aligned.sortedByCoord.out.bam",
              "bam1_3/Aligned.sortedByCoord.out.bam","bam1_4/Aligned.sortedByCoord.out.bam",
              "bam1_5/Aligned.sortedByCoord.out.bam","bam1_6/Aligned.sortedByCoord.out.bam",
              "bam1_7/Aligned.sortedByCoord.out.bam","bam1_8/Aligned.sortedByCoord.out.bam",
              "bam1_9/Aligned.sortedByCoord.out.bam","bam1_10/Aligned.sortedByCoord.out.bam",
              "bam1_11/Aligned.sortedByCoord.out.bam","bam1_12/Aligned.sortedByCoord.out.bam",
              "bam2_2/Aligned.sortedByCoord.out.bam","bam2_3/Aligned.sortedByCoord.out.bam",
              "bam2_4/Aligned.sortedByCoord.out.bam","bam2_5/Aligned.sortedByCoord.out.bam",
              "bam2_6/Aligned.sortedByCoord.out.bam","bam2_7/Aligned.sortedByCoord.out.bam",
              "bam2_8/Aligned.sortedByCoord.out.bam","bam2_9/Aligned.sortedByCoord.out.bam",
              "bam2_10/Aligned.sortedByCoord.out.bam","bam2_11/Aligned.sortedByCoord.out.bam",
              "bam2_12/Aligned.sortedByCoord.out.bam","bam2_13/Aligned.sortedByCoord.out.bam",
              
targets  <- data.frame(row.names = paste0('Sample_',c(1:24)),bam = BAMFiles[1:24],f1 = rep(c("O","B"),times=c(12,12)),stringsAsFactors = FALSE)

# Counting against Annotated Features ----
gbcounts <- gbCounts(features=features, targets=targets, libType="PE", minReadLength = 200, maxISize = 50000)

# Junction Based Denovo and splicing estimation ----
asd <- jCounts(counts=gbcounts, features=features, libType="PE", minReadLength=200)
Is the code correct?

Why do I get all NAs ? No event is found

**binGenome(TxDb)** output:
* Number of extracted Genes = 60624
* Number of extracted Exon Bins = 640410
* Number of extracted intron bins = 522555
* Number of extracted trascripts = 227887
* Number of extracted junctions = 383393
* Number of AS bins (not include external) = 92991
* Number of AS bins (include external) = 94867
* Classified as:
        ES bins = 31985 (34%)
        IR bins = 13085 (14%)
        Alt5'ss bins = 10158    (11%)
        Alt3'ss bins = 10909    (12%)
        Multiple AS bins = 26854        (29%)
        classified as:
                        ES bins = 8450  (31%)
                        IR bins = 5452  (20%)
                        Alt5'ss bins = 5151     (19%)
                        Alt3'ss bins = 6464     (24%)

**Comment by estepi** [comment]
Hi Onkar, 

Can you open this issue here?
https://github.com/chernolab/ASpli/issues

I see you have: 24 samples 12 and 22 in each group
If you have your gbcounts object already done, we can inspect it and see how is the coverage in general you have

Maybe it is a good idea to split data by chunks... or to merge replicates to have a first idea 

Which is your question here? Compare one group against the other?

We did run 50 control vs 50 treat and ASpli did well

thanks in advance

**Comment by OnkarMulay** [comment]
Ok, sure I'll open there and post the gbcounts there only.
No, my question is what has happened that I get NA everywhere in : **asd** <- jCounts(counts=gbcounts, features=features, libType="PE", minReadLength=200)

Thank you
